version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build:
      context: .
    command: bundle exec rails s puma -p 3000 -b '0.0.0.0'
    volumes:
      - .:/my-blog
    ports:
      - "3001:3000"
    depends_on:
      - db